apiVersion: v2
name: envoy-gateway
description: "A Helm chart for Envoy Gateway"
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: gateway-helm
  version: 1.6.1
  repository: oci://docker.io/envoyproxy
  condition: gateway-helm.enabled
