apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: eg
  listeners:
  - name: http
    port: 80
    protocol: HTTP
  - name: https
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: tls
---
apiVersion: v1
data:
  tls.crt: {{ .Files.Get "files/www.example.com+1.pem" | b64enc }}
  tls.key: {{ .Files.Get "files/www.example.com+1-key.pem" | b64enc }}
kind: Secret
metadata:
  name: tls
type: kubernetes.io/tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: backend
spec:
  targetRefs:
    - group: "backend"
      kind: Service
      name: backend
      sectionName: https
  validation:
    hostname: example.com
    wellKnownCACertificates: "System"
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: frontend
spec:
  targetRefs:
    - group: "frontend"
      kind: Service
      name: frontend
      sectionName: https
  validation:
    hostname: example.com
    wellKnownCACertificates: "System"
