apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: eg
  listeners:
  - name: http
    port: 80
    protocol: HTTP
  - name: https
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: tls
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVRVENDQXFtZ0F3SUJBZ0lRVDg0ZUluSkprQWtJRkszYmtVSkVGekFOQmdrcWhraUc5dzBCQVFzRkFEQnoKTVI0d0hBWURWUVFLRXhWdGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZ1EwRXhKREFpQmdOVkJBc01HM1J2Ym5rdQpjRUJVVnpFMk9EQXlNREl3TkUwdE15NXNiMk5oYkRFck1Da0dBMVVFQXd3aWJXdGpaWEowSUhSdmJua3VjRUJVClZ6RTJPREF5TURJd05FMHRNeTVzYjJOaGJEQWVGdzB5TlRFeU1qTXdPRFU1TlRGYUZ3MHlPREF6TWpNd09EVTUKTlRGYU1FOHhKekFsQmdOVkJBb1RIbTFyWTJWeWRDQmtaWFpsYkc5d2JXVnVkQ0JqWlhKMGFXWnBZMkYwWlRFawpNQ0lHQTFVRUN3d2JkRzl1ZVM1d1FGUlhNVFk0TURJd01qQTBUUzB6TG14dlkyRnNNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3aUpBYWJ5RkRVb2UvRUxBTjlWcmhZdEZkajE0WGM2Wnd5RWgKdEJ3aVpsUjdJdCtVcGhtWHdIUkQvLzBrTzc3RlhmOUpmVWtXcnowaUFPNWt2OTVzQmxjVkNMYks4a01IeDFEago3dlFpMWlEbXNqak9kTUgwNG1QdGRtSkxKY09yZ05ROHZxRGdhYjJjQytPVnlXWmx6MXh3TlhzVlVNVENhTmlmCjEwYmlaODdxTHBSS1NYREk0MFdvaGdyMUNiaVJlQVBXNkJLOC9mWjl2TU95WjArZHA0Z2ViNlJlb0U5N0paZmQKWFRRdDIrTm82YXhaeiszUGRoS0hhYm9kS3UyNFlFMHlhRVUxMUh0R3NQOGVDeUh3K1RONmFtcUxjbFdhRFJNcAo5Yy82K2wrS2dxZGtPOTBianJIN29uTUNOODJkVjVVOGYwcExVNGt6N2tERWowYkVFd0lEQVFBQm8zVXdjekFPCkJnTlZIUThCQWY4RUJBTUNCYUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0h3WURWUjBqQkJnd0ZvQVUKbXlJNHpDVWNEZjJ2TnBHclc3KzlnemYwK05zd0t3WURWUjBSQkNRd0lvSVBkM2QzTG1WNFlXMXdiR1V1WTI5dApnZzloY0drdVpYaGhiWEJzWlM1amIyMHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnR0JBTnFLeWwzM3BicDBnU3N0CkFuUmh4RHpnRXJ1emlxbGRjR3M5dE0xODR1ZHhQTkp6eVVGdGFYWlo4QXJwcVFMNldQV0JNYWZaZ3AwRnJWdHMKUGEwSVVJSThiSGo0ZEtVYTVqQmZVSmhFZ1JkQ0tab2ZRSk1pN3hNYitpQ3NqVHlkME9XNUF3Y0dmYWdaTC8yagpmWEZ1U05sQWpkQ0lVQ0NNZXJ0c21KMUsvYzl2SG42Y2w2L1MvVytyczA5NWNiSE1uZnp6L2t4TmthczhGU29uCm5rQ1lrL3BVTXZBR2dpaXFpdkhQbnFCOWcwcExSRGRKbVVVZzlDVWtBNEY5bnoxMnpMaiswZlZtVG5mVk5LbjYKQzcwczJybXFjTU5PNWJCUVNGODNXbkE3dlhuZU1yaXVCMXJGUSthajBKeDRiOUNZVmJJRm54aEJPdWd6TjJVWAp2VkUxWk1kU2hnWTNtM1BuQWZlMFViOFAxNm44WjVDTHRKTjNDemZKeHFaQzFMQXVLbGRnaFlPSXhYMk9PSFZVCmtzdjJENFJWTkVWZkNOR1lMU1Y0NlcrVnRJb3ZNL05mZ090Y0RpY1lxSkFQQ21tSnl4Q21vUy9wTmg5NzFyYVUKS2JpdU83YmlXMktiSFFlSE4vei94WGY4c08vTkZ6TXlhWGFZSmVJZmFDSHNZZnN2OFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRENJa0JwdklVTlNoNzgKUXNBMzFXdUZpMFYyUFhoZHpwbkRJU0cwSENKbVZIc2kzNVNtR1pmQWRFUC8vU1E3dnNWZC8wbDlTUmF2UFNJQQo3bVMvM213R1Z4VUl0c3J5UXdmSFVPUHU5Q0xXSU9heU9NNTB3ZlRpWSsxMllrc2x3NnVBMUR5K29PQnB2WndMCjQ1WEpabVhQWEhBMWV4VlF4TUpvMkovWFJ1Sm56dW91bEVwSmNNampSYWlHQ3ZVSnVKRjRBOWJvRXJ6OTluMjgKdzdKblQ1Mm5pQjV2cEY2Z1Qzc2xsOTFkTkMzYjQyanByRm5QN2M5MkVvZHB1aDBxN2JoZ1RUSm9SVFhVZTBhdwoveDRMSWZENU0zcHFhb3R5VlpvTkV5bjF6L3I2WDRxQ3AyUTczUnVPc2Z1aWN3STN6WjFYbFR4L1NrdFRpVFB1ClFNU1BSc1FUQWdNQkFBRUNnZ0VBZXNvSFM5bTlua1kvaXZiOWRWTThDdCtvTTcxMW9IL0lxYThQRGtpdFNXUXQKN2tUVVZLcmpYUXNzNTRGSnBiQm9UYWZtNTZPUEFZLzlMZkdiTC9DVEN2K1JnazE3MS9lbHQ5L21DNEhIZHdDZwphaUdjRkNXSnFwZmgzbnNWWlBGNlRLWHhOZkd6ZjY0NlFSclY1dWtwaEJySHJrd0hrMnFnUElpbnNSWllwYWNTClhiU0V6TGFTVVUrVUFCb0psRG1uY3RuR0MxNmhrSDBPSVlaTjFSdldldU9rMXJRZnV0WmUxU0JoL2tKTjl0ZHUKWHhhdkxvMnRhdUVyZmZ4VEd4ek1lWDBsSzZjUldOMlhNTE5uaWhob3htUERwYXdCZkhvWTV6M3ZIN1lYTVV2NQpmRjJCVGFMdlM5UGdWQzg0WWY1d2MvalBZQ1J1ZXJXVnBBOGd3TTFWb1FLQmdRRDdHTkY5QWJ6TVVnWjRkU1pICnJUTE5LS1VsWk9tZU9KQnBjdS9MbTJLVmtmV0Zoa0pCQkMzWjFNWjhEbzI5cFlWdVd0b1p2dS8xczNsRVd0V0YKdE5yL0tRLzAzN00xYWNUMWNyOTkwWm5PUzZtSXhYcXh4d3BVRGhMZ0xHSE5NMFZnWWpsaXQ2c3kwd3F1dStRTwpQTW5rS24yYjkrU25RN2dHUFFsbVhrRVlOUUtCZ1FERjdLK3cxc25PT1luYmp0NEwzTFpvMnZ3NGUrVEpBYnVQCm8vM3pVeVFyL0dsZWhmaXF4VkxOMVlkWmp3eTdzdEJGOWgrMHFIM1FVZStQZnN6RlhRWk00TGZtZjdtZWw2RVkKem9ZNThhVkVnUXVBQUJnWTIyc29KWEpVSUpuSmI5U29OY2VSMXBReW1udHRLYWZBYXRRdDNBaDJtZi95TGNnaQppbm9QenZaRUp3S0JnUUNEK2NGeDRNM28zbHdFU0I2OG9hNEg0d3NhSW5ZZjhUOEdEYUUzOVEzVjY0ZU9qTWlaCi82WlJ6ZUlkSmxFZGtyZ1ZEcTkveExtKy9Id0tqMnVYQVQzeHl4VlY4Wlh4eHd2OHJqa3oya3pxL3gyMmc0VS8KbDR3NExjV0NDaEhGbHVNcUM3WjV5bXV6SlBXQ2JjTXFNSTAwM1poenQ5RjRrTUZTbGhZd3RlMmsyUUtCZ1FDcgphN0JLNyt4KzhUU2w5Vm41V2lLZU5EUEkwLzAxM290TkFCSzlnTi9PUE9JaDNOU2ZTeUhKWmt2QTFIV0p4M2c5CmI4ck1GRFpMaS90NUE3QmtxNG4rWVk3RlV4QTMvRW1waTQyVGQrZlVxaE9FdkJBaXp6OUMyUlBwS3djbkFQVmsKN3BjM2gycDVYWFRTK2dYeFVGVU9sd2k1ZCszR0djTEJyNy9DRzFVTmR3S0JnSGRIT1gzRVRJYnlPMVBySDhUTQpJUDZGREZKSmZhQ2lDWkc0ZmNib1pCVFYwMm1SVFlXTUpmdUU5UzBwMVpLd1YzdUxvejY4SE5iV2xwVkw0ZlR6ClZoUGtQZWsxUHpQWUw4M2NTSXExdkcwZXpmM3ljY2p6MkFDaDZlQXhxbWg4cTNodUNRVjMzTEsxRUtScUl5N1YKZzBRSklRdnlWemZFMGU1NVVLQ01Pd0FCCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: tls
type: kubernetes.io/tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: backend
spec:
  targetRefs:
    - group: "backend"
      kind: Service
      name: backend
      sectionName: https
  validation:
    hostname: example.com
    wellKnownCACertificates: "System"
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: frontend
spec:
  targetRefs:
    - group: "frontend"
      kind: Service
      name: frontend
      sectionName: https
  validation:
    hostname: example.com
    wellKnownCACertificates: "System"
