apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend
spec:
  parentRefs:
    - name: gateway
  hostnames:
    - {{ .Values.host.web }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 8000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-private
spec:
  parentRefs:
    - name: gateway
  hostnames:
    - {{ .Values.host.web }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/private
      backendRefs:
        - name: frontend
          port: 8000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: gateway
  hostnames:
    - {{ .Values.host.api }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: backend
          port: 8000
