apiVersion: v1
kind: Secret
metadata:
  name: https-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/www.example.com+1.pem" | b64enc }}
  tls.key: {{ .Files.Get "files/www.example.com+1-key.pem" | b64enc }}
